### ISSUE TITLE
Add more TODOs and modify the table's columns

### ISSUE THREAD

**Issue by Dorfieeee** [dgupta0/todo-ant#1]
https://github.com/dgupta0/todo-ant/blob/f02abc513e22a47353bc04a0f4df1ffe6a6ef85b/server.js#L10-L17

Let the Mock API return 20 todo objects. Moreover, add missing properties as defined in the description below.
Try to use ChatGPT to generate those for you. ( Copy-pasting the requirements and asking for 20 such object should do it )

![image](https://user-images.githubusercontent.com/65303812/232237069-6c6f770b-7a45-44e2-ac27-3fcc838ec506.png)

Finally, modify the table's columns to reflect this change.

**Comment by dgupta0** [comment]
done!
